version: 0.0.{build}-ci
image: Visual Studio 2017
init:
- ps: >-
    $tagRelease = $env:APPVEYOR_REPO_TAG -eq 'true'

    if ($tagRelease) {
      $tag = $env:APPVEYOR_REPO_TAG_NAME
      Update-AppveyorBuild -Version "$tag"
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: dotnet build -c Release
test_script:
- ps: dotnet test -c Testing -p:CollectCoverage=true .\tests\Spectaris.Tests\Spectaris.Tests.csproj
artifacts:
- path: .\src\Spectaris\bin\Release\net462\Spectaris.dll